In [4]:
with open("../../data/day04.txt") as f:
    #creates a list of the binaries
    data = [list(line.strip()) for line in f]
    
    print(data[0][0:2])

['2', '3']


In [100]:
import numpy as np

with open('../../data/day04.txt', 'r') as f:
    lines = [entry.strip() for entry in f.readlines()]
    #print(lines)
    
    #get just the called numbers as a list of integers
    called_numbers = [int(entry) for entry in lines[0].split(',')]
    print(type(called_numbers))
    #print(called_numbers)
    
    #seperate out the boards
    number_of_boards = (len(lines)-1)//6
    print(number_of_boards)
    bingo_boards = dict()
    for j in range(number_of_boards):
        line_subset = lines[(2 + j*6):(2+5+(j+1)*6)]
        this_board = np.zeros((5,5), dtype=int)
        for i in range(0,5):
            line_entries = [int(entry) for entry in line_subset[i].split(' ') if entry != '']
            this_board[i] = line_entries
            
        bingo_boards[j] = this_board
    
    print(bingo_boards[0])
    
    #create boards to count filled with same structure
    bingo_scores = dict()
    for j in range(number_of_boards):
        this_board = np.zeros((5,5), dtype=int)
        bingo_scores[j] = this_board
        
    print(bingo_scores[0])
    print(type(bingo_boards))
    print(len(bingo_boards))
    print(range(len(bingo_boards)))

          
    round_count = 0 
    game_over = 0
    for this_num in called_numbers:
        round_count += 1
        
        for card in range(len(bingo_boards)):
#         for card in range(5):
            this_card = bingo_boards[card]
#             print(this_card)
            
            if this_num in this_card:
                
                indices = np.where(this_card == this_num)
#                 print(indices)
                bingo_scores[card][indices[0], indices[1]] = 1
#                 print(bingo_scores[card])
            
            #check for bingo
            row_bingo = list(np.sum(bingo_scores[card], axis = 1))
            col_bingo = list(np.sum(bingo_scores[card], axis = 0))
#             print(type(col_bingo))
#             print(col_bingo)
            all_bingo =  col_bingo + row_bingo
#             print(all_bingo)
            if 5 in all_bingo:
                print("winning number:", this_num)
                print("rounds needed:", round_count)
                print("winning card:", card)
                win_card = bingo_boards[card]
                win_score = bingo_scores[card]
                last_num = this_num
                game_over = 1
                
        if game_over==1:
            break
    #get sum of unmarked numbers
    indices  = np.where(win_score==0)
    print(indices)
    score = win_card[indices[0], indices[1]]
    print(score)
    #then multiply by the last number called
    print(sum(score)*last_num)
    

<class 'list'>
100
[[67 97 50 51  1]
 [47 15 77 31 66]
 [24 14 55 70 52]
 [76 46 19 32 73]
 [34 22 54 75 17]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'dict'>
100
range(0, 100)
winning number: 42
rounds needed: 32
winning card: 23
(array([0, 0, 0, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 4, 0, 1, 2, 0, 3, 4, 0, 1, 2, 3, 4]))
[24 19 78 69 52 38  7 44 45 49 94 51 98 99 27]
33348
